### ISSUE TITLE
Problem of access rights on folder doc/export, Problema de derechos sobre la carpeta doc/export

### ISSUE THREAD

**Issue by miloaec** [asanzdiego/markdownslides#20]
When creating a new presentation or trying updating one, the script build.sh change the folder doc/export rights to 666, and must be 750 or 755. So the scipt fail and the files in folder are not accessible.

In build.sh I think you can remove or comment the line 454. Because it apply the 666 rights not only to the files but to the folder too, then line 455 do not apply. 

After commenting out the line 454, it works for me. I am using GNULinux/Debian 9.

Regards.

Cuando hago una nueva presentacion o trato de modificar una antigua, el script build.sh modifica los derechos de la carpeta doc/export y los pone a 666, pero normalment deberian ser 750 o 755. Entonces el script no fonctionna y no se puede acceder a los archivos en la carpeta.

En el archivo build.sh, creo qui usted puede borrar o commentar la linea 454. Por que esta linea applica los derechos 666 no solo a los archivos contenidos en la capeta pero tambien a la carpeta misma, entonces la linea 455 no fonctionna.

Despues de commentar la linea 454 todo fonctionna bien para mi. Estoy usando GNULinux/Debian 9.

Atentamente.

**Comment by asanzdiego** [comment]
Thank you for reporting the issue. The problem with permissions comes only when you run MarkdownSlides from Docker because you have to do it as root user. If you don't run MarkdownSlides from Docker you don't need to change permissions. But if you do, you have to change permissions (755 for folders and 666 for files). I think I fixed it with your help :-)

Regards.

Gracias por informar de este issue. El problema con los permisos viene sólo cuando se ejecuta MarkdownSlides desde Docker porque hay que hacerlo como usuario root. Si no se ejecuta MarkdownSlides desde Docker no se necesitan cambiar permisos. Pero si se hace, hay que cambiar los permisos (755 para carpetas y 666 para archivos). Creo que lo he arreglado con tu ayuda :-)

Saludos.
